### ISSUE TITLE
Can you add a transpired version to the build?

### ISSUE THREAD

**Issue by ericwooley** [hakimelek/storybook-window-size#1]
I'm using typescript so I don't have the loaders available to transpile this. 

I like the idea though!

**Comment by hakimelek** [comment]
Sure! I will try to find some time to work on the transpiled version next. However, PRs are more than welcome!

**Comment by hakimelek** [comment]
@ericwooley, I have added a transpiled build to the project. However, the same feature that this add-on is brining up already exist on storybook itself. It's funny that I was not aware of its existance until I resized the iframe on the the panel resizers. I always had a tendency of to resize the window on the browser itself. Let me know your thoughts about adding new features that could be helpful in the scope of this add-on.
